name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install .NET 7
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 7.0
          echo "$HOME/.dotnet" >> $GITHUB_PATH
      - uses: retypeapp/action-build@latest
      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
